### ISSUE TITLE
Add new kinds for full Maki icon library support

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1423]
Around 47:

- [ ] !!! **airfield** - http://wiki.openstreetmap.org/wiki/Tag:military%3Dairfield (also landuse, and pois if has name)
- [x] **barrier** - we have a lot of these already, maybe add a few more? https://taginfo.openstreetmap.org/keys/barrier#values http://wiki.openstreetmap.org/wiki/Key:barrier
- [x] **blood_bank** – http://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dblood_donation and http://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dblood_bank
- [x] **danger** - could add http://wiki.openstreetmap.org/wiki/Tag:military%3Ddanger_area (also landuse and pois if has name), and for sea marks (see https://github.com/tilezen/vector-datasource/issues/822). 16/51.8513/0.8902
- [x] **defibrillator** - http://wiki.openstreetmap.org/wiki/Tag:emergency%3Ddefibrillator
- [ ] !!! **entrance** - http://wiki.openstreetmap.org/wiki/Key:entrance – would this go into the buildings layer not pois?
- [x] **gaming** - http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dadult_gaming_centre
- [x] **garden_centre** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dgarden_centre
- [x] **golf** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dgolf (we already have golf_coarse, so I think this is for a golf store
- [x] **grocery** - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dgrocery and related http://wiki.openstreetmap.org/wiki/Tag:shop%3Dgreengrocer
- [x] **harbor** - http://wiki.openstreetmap.org/wiki/Harbour
	- [x] harbour=yes or landuse=harbour 15/51.4963/-2.7199
	- [x] military=**naval_base** 17/52.37419/4.91787
	- landuse=* tag values with their specific usage:
		- [x] landuse=**port_terminal** 18/-27.36735/-55.98510
		- [x] landuse=**ferry_terminal** (we have poi but not landuse?) 19/54.14756/-4.47411
		- [x] landuse=**container_terminal** 16/49.4824/0.1768
		- [x] landuse=**shipyard** 16/45.0595/12.2517
		- [x] landuse=**wharf** 19/53.79418/-1.53600
		- [x] landuse=**quay** 16/51.9451/1.0824
	- we already have leisure=marina and waterway=dock
	- Other features directly related to harbours
		- [x] waterway=**boatyard** - see https://github.com/tilezen/vector-datasource/issues/673
		- [x] waterway=**boat_lift**
		- [x] shop=**ship_chandler**
		- [x] man_made=**crane** - stationary, permanent crane - see https://github.com/tilezen/vector-datasource/issues/1417.
		- [x] amenity=**customs**
		- [x] amenity=**harbourmaster**
		- [x] **mooring**=* – tell me more...
		- [x] man_made=**quay** 19/51.52862/-0.24830
		- [x] **sanitary_dump_station**=* - Septic waste pumpout facility 
		- [x] **waterway=fuel** or seamark:small_craft_facility:category=fuel_station (separate from amenity=fuel)	
- [x] **heliport** - related https://github.com/tilezen/vector-datasource/issues/1277 and http://wiki.openstreetmap.org/wiki/Tag:aeroway%3Dheliport
- [x] **horse_riding** – related to https://github.com/tilezen/vector-datasource/issues/670 and http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dhorse_riding
- [ ] **industry** (why isn't this in landuse already?) is it a catch all for any http://wiki.openstreetmap.org/wiki/Key:industrial that we don't already filter for (see shop)?
- [x] **karaoke** 
	- amenity:karaoke_box http://wiki.openstreetmap.org/wiki/Proposed_features/Karaoke_box
	- amenity:karaoke
	- ~~leisure:karaoke~~
- [x] "lodging"
	We already have: tourism=[hotel,chalet,guest_house,hostel,motel].
	~~We could add: **amenity=love_hotel** – but this would need to be min_zoom 18?~~
- [ ] **logging** - http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dlogging surprisingly in the 10,000 of uses! would be landuse
- [ ] !?! **parking_garage**. We already include http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking, but we could also include http://wiki.openstreetmap.org/wiki/Key:parking tags and promote [multi-storey,underground,rooftop] to kind:parking_garage?
- [ ] !!! **residential_community** ???
- [ ] !!! **roadblock** - Barrier:obstacle_type=roadblock http://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Tags/Humanitarian_Data_Model
- [x] **rocket** - possibly http://wiki.openstreetmap.org/wiki/Tag:military%3Drange with extra bits, or some sort of spaceport thing like SpaceX? 12/51.5805/0.9834
- [ ] !!! **scooter** - related to shop=motorcycle? http://wiki.openstreetmap.org/wiki/Key:motorcycle:type
- [x] **shelter** – related to https://github.com/tilezen/vector-datasource/issues/670 and http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dshelter
- [x] **shop** – when it doesn't match any other shop=* value?
- [x] **slaughterhouse** http://wiki.openstreetmap.org/wiki/Tag:industrial%3Dslaughterhouse
- [x] **snowmobile** – we have this for roads but not landuse/pois? http://wiki.openstreetmap.org/wiki/Tag:shop%3Dsnowmobile
	- [x] shop=**snowmobile**
	- [x] shop=**atv** - ATV / Quad shop
	- [ ] !!! shop=**boat** - Boat shop

**Comment by zerebubuth** [comment]
> **entrance** - http://wiki.openstreetmap.org/wiki/Key:entrance – would this go into the buildings layer not pois?

I'm not sure it makes sense in POIs, perhaps buildings would be more appropriate.

The entrance seems like something that isn't useful by itself, and we would want to link the entrance to the POI (or POIs) that it is the entrance to? So that it's possible, when highlighting a large department store or station, to see the entrances for the highlighted feature. But by themselves perhaps they'd only be visible at some very high zoom like z19+?

**Comment by nvkelso** [comment]
`entrance` smells vaguely of https://github.com/tilezen/vector-datasource/issues/1305 indoor mapping, too. But I think it's generally useful enough like address numbers to include at z19+ in buildings.

**Comment by nvkelso** [comment]
`atv` and `karaoke_box` need icons

QA followup in: 

- shop=boat https://github.com/tilezen/vector-datasource/issues/1581
